[versions]
agp = "8.13.1"
firebase-messaging-Ktx = "24.1.2"
firebase-analytics-ktx = "22.5.0"
firebase-bom = "34.5.0"
googleServices = "4.4.4"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
androidx-hilt-navigation-compose = "1.3.0"
hilt-android = "2.57.2"
hilt-compiler = "2.56.2"
hilt-ext = "1.3.0"
appcompat = "1.7.1"
material = "1.13.0"
uiToolingPreviewAndroid = "1.9.4"
ksp = "2.2.10-2.0.2"
room = "2.8.3"
retrofit = "3.0.0"
okhttp = "5.3.0"
gson = "2.13.2"
coroutines = "1.10.2"
work = "2.11.0"
navigation = "2.9.6"
coil = "2.7.0"
#mapboxSdk = "11.16.1"
#mapboxCompose = "11.16.1"
#mapboxNagivation = "2.12.0"
mapbox-maps = "11.15.1"
#mapbox-navigation = "2.12.0"
composeUi = "1.9.4"
serialization = "1.9.0"
secrets-gradle = "2.0.1"
accompanist = "0.36.0"
tvMaterial = "1.0.1"
foundationLayout = "1.9.4"
playServicesLocation = "21.3.0"
firebaseInappmessagingDisplay = "22.0.2"
firebaseCrashlytics = "20.0.3"
googleFirebaseCrashlytics = "3.0.6"
firebaseMessaging = "25.0.1"
material3 = "1.4.0"
foundation = "1.9.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
# Firebase
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "firebase-messaging-Ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }

# Retrofit & Gson
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
#hilt
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt-android" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android" }
hilt-dagger = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
# Work Manager
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
work-hilt = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-ext" }
# Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
# Coil
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
#Mapbox
#mapbox-sdk = { group = "com.mapbox.maps", name = "android", version.ref = "mapboxSdk" }
#mapbox-compose = { group = "com.mapbox.extension", name = "maps-compose", version.ref = "mapboxCompose" }
#mapbox-navigation = { module = "com.mapbox.navigation:router", version.ref = "mapboxNagivation" }
#mapbox-navigation-core = { module = "com.mapbox.navigation:android", version.ref = "mapboxNagivation" }
mapbox-maps = { module = "com.mapbox.maps:android", version.ref = "mapbox-maps" }
#mapbox-navigation = { module = "com.mapbox.navigation:android", version.ref = "mapbox-navigation" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
androidx-tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tvMaterial" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
firebase-inappmessaging-display = { group = "com.google.firebase", name = "firebase-inappmessaging-display", version.ref = "firebaseInappmessagingDisplay" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }



[bundles]
dagger-impFl = [
    "androidx-hilt-navigation-compose",
    "hilt-dagger",
]
dagger-ksp = [
    "hilt-android-compiler"
]
room-impl = [
    "room-runtime",
    "room-ktx",
]
room-ksp = [
    "room-compiler",
]
retrofit = [
    "retrofit",
    "converter-gson",
    "okhttp",
    "gson",
]
coroutines = [
    "coroutines-core",
    "coroutines-android",
]
work = [
    "work-runtime-ktx",
    "work-hilt",
]
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
secrets-gradle = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets-gradle"}
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "googleFirebaseCrashlytics" }

